# Generated by Django 4.0 on 2021-12-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('responsavel', models.CharField(blank=True, max_length=500, null=True)),
                ('telefone', models.CharField(blank=True, max_length=500, null=True)),
                ('descricao', models.CharField(blank=True, max_length=3000, null=True)),
                ('secretaria_imediata', models.CharField(blank=True, max_length=500, null=True)),
                ('setor_imediato', models.CharField(blank=True, max_length=500, null=True)),
                ('nivel_hierarquia', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
    ]
