# Generated by Django 4.0 on 2021-12-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='secretaria_imediata',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='setor',
            name='setor_imediato',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
